### ISSUE TITLE
Scraping indie game subreddits for developers and games

### ISSUE THREAD

**Issue by andygello555** [andygello555/game-scout#2]
## Proposition
This would be a process that is very similar to the current Twitter scraping process.
We will need to check the following subreddits daily:
- r/GameDevelopment
- r/SoloDevelopment
- r/gamedesign
- r/IndieDev
- r/truegamedev
- r/gamedev
- r/IndieGaming.
- r/gamedevscreens
## What will need to change
- New tables
  - RedditDeveloper table to track individual developers found on Reddit
  - RedditDeveloperSnapshot table to save the snapshots of RedditDevelopers to
- Need to alter the Games table to include references to RedditDevelopers (probably in a new array column)
- Need to create a whole new scraping process for Reddit
   - Either add more Phases to the Scout procedure
   - Or add a completely new set of Phase.Runs for the Reddit scrape
- Would also need to add a bunch more cached fields to the ScoutState object

How will scraping work?
- Discovery
  - Fetch the top X posts divided equally between the subreddits mentioned above + max Y comments for each post
  - For each Post we will see if we can extract any game URLs from the:
    - Post title
    - Post body
    - Any of the comments from the OP
  - Aggregate post metrics + comment engagement + author's karma
  - Run any Game URLs through the storefront scrapers
- Update (this will probably need to run after the Twitter updates have ended because they need to be synced up in entirely different ways).
  - Any Developers marked as Reddit devs we will fetch the posts that they have made to the subreddits mentioned above in the last 7 days
  - Aggregate post metrics + comment engagement + author's karma

TODO implementation:

- [x] These two updated columns now take usernames of both Reddit and Twitter users. Twitter usernames will be prefixed with `"T"` and Reddit usernames will be prefixed with `"R"`. We need to double check the usages of these fields, as well as their DB column counterparts, to ensure that we are setting and using these fields properly after these changes
  - [x] Check all usages of `Game.Developers` as well as its column: `games.developers`
  - [x] Check all usages of `Game.VerifiedDeveloperUsernames` as well as its column: `games.verified_developer_usernames`
- [x] We need to add new versions of the `UserTweetTimes` and `DeveloperSnapshots` cached fields for Reddit developers
- [x] Update `Discovery` phase
  - [x] Create `TestDiscoveryPhase` test
- [x] Update `Update` phase
  - [x] Update `TestUpdatePhase` test
- [x] Update `Snapshot` phase
  - [x] Update `TestSnapshotPhase` test
- [x] Update `Disable` phase
  - [x] Update `TestDisablePhase` test
- [x] Update `Enable` phase
  - [x] Update `TestEnablePhase` test
- [x] Update `Delete` phase. Wasn't that hard to update as we don't need to distinguish between the different Developer types here
  - [x] ~~Update `TestDeletePhase` test~~
- [x] Update `Measure` phase
  - [x] Change wording in Measure emails regarding Twitter developers
    - [x] Need to use `RedditPostIDs` sometimes instead of `TweetIDs`
  - [x] New Reddit "From" label needed in linked Monday board + need to change Monday config to find where a game was found by looking at its developers
  - [x] Add a test for the `Measure` phase
    - [x] Need a new mapping config for tests + new Monday board
- [x] Add the new Reddit metric fields in DeveloperSnapshot as weighted fields
  - [x] RedditPublicMetrics
  - [x] PostPublicMetrics
- [x] SubredditFetch procedure should check rate limits for non-paginateable bindings
- [x] Add new constants to README

TODO after implementation:

- [ ] Set `developers.type column` to `"T"` (for TwitterDeveloperType): `update developers set type = 'T';`
- [ ] Prefix each developer username in `games.developers` with `"T"` (for TwitterDeveloperType) for each `Game` in `games`: `update games set (developers, verified_developer_usernames) = (array(select 'T' || unnest from unnest(developers)), array(select 'T' || unnest from unnest(verified_developer_usernames)));`
- [ ] Same thing as the above for the `games.verified_developer_usernames` column
- [x] ~~Set `developers.current_reddit_*` to 0? Might not need to because we might check for nil anyway for `RedditPublicMetrics`~~ [Gorm always returns the empty embedded struct even if all columns in the struct are null in the DB](https://github.com/go-gorm/gorm/issues/5431)
- [x] ~~Set `developer_snapshots.reddit_user_*` to 0? Might not need to because we might check for nil anyway for `RedditPublicMetrics`~~ [Gorm always returns the empty embedded struct even if all columns in the struct are null in the DB](https://github.com/go-gorm/gorm/issues/5431)
- [x] ~~Set `developer_snapshots.total_post_*` to zero values? Might not need to because we might check for nil anyway for `PostPublicMetrics`~~ [Gorm always returns the empty embedded struct even if all columns in the struct are null in the DB](https://github.com/go-gorm/gorm/issues/5431)
- [ ] Might need to set `developer_snaphots.reddit_post_ids` to its default
- [ ] Make sure the new config.json constants and Monday values are changed to their appropriate values
- [ ] Might need to increase `constants.scout_timeout` in config.json

Monday.com Item ID: #3806777653
